Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/shopping/urls.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     urls
   Author :       hyt
   Create date：          2018/10/31
-------------------------------------------------
"""
from django.urls import path
from . import views

app_name = 'shopping'
urlpatterns = [
    path('', views.home, name='home'),
    path('<phone_id>/', views.single_web, name='single_web'),
    path('<phone_id>/<good_id>/', views.good_detail, name='good_detail')
]

Shop/shopping/models.py
from django.db import models


# Create your models here.
class ShopList(models.Model):
    name = models.CharField(max_length=50, unique=True)         # 类别名称
    disc = models.TextField(max_length=100, blank=True)         # 类别描述
    photo = models.ImageField(upload_to='category', blank=True) # 类别图片

    class Meta:
        # 这个选项是指定，模型的复数形式是什么，比如：verbose_name_plural = "stories"
        verbose_name_plural = "ShopList"
        # 指定表名
        db_table = "ShopList"

    def __str__(self):      # python3 在管理后台显示数据名称（若没有这个只显示对象），python2为__unicode__(self)
        return self.name


class ProdList(models.Model):
    name = models.CharField(max_length=50, unique=True)             # 商品名称
    disc = models.TextField(max_length=100, blank=True)             # 商品描述
    photo = models.ImageField(upload_to='category', blank=True)     # 商品图片
    price = models.DecimalField(max_digits=10, decimal_places=2)    # 商品价格
    # 所属类型，跟随ShopList表更改
    typer = models.ForeignKey(ShopList, on_delete=models.CASCADE)   # 商品类型
    having = models.IntegerField(default=0)                         # 库存
    havup = models.BooleanField(default=True)                       # 是否上架
    creatime = models.DateTimeField(auto_now_add=True)              # 创建时间
    moditime = models.DateTimeField(auto_now_add=True)              # 修改时间

    class Meta:
        verbose_name_plural = "ProdList"
        ordering = ['creatime']     # 按照创建时间来排序
        db_table = "ProdList"

    def __str__(self):
        return self.name

Shop/shopping/views.py
from django.shortcuts import render, get_object_or_404
from . import models


# Create your views here.
def home(request):
    # 所有商品类别
    alltypes = models.ShopList.objects.all()
    # 类型与商品
    type_and_goods = []
    for typer in alltypes:
        type_and_goods.append((typer, models.ProdList.objects.filter(typer=typer, havup=True)))
    content = {'type_and_goods': type_and_goods, 'alltypes': alltypes}
    return render(request, 'shopping/home.html', content)


def single_web(request, phone_id):
    alltypes = models.ShopList.objects.all()
    # 所属类别
    blg_cgy = get_object_or_404(models.ShopList, id=phone_id)
    # 类型与商品
    type_and_goods = [(blg_cgy, models.ProdList.objects.filter(typer=blg_cgy, havup=True))]
    content = {'type_and_goods': type_and_goods, 'alltypes': alltypes}
    return render(request, 'shopping/home.html', content)


def good_detail(request, phone_id, good_id):
    # 根据商品ID获取商品详细信息
    gd_detail = get_object_or_404(models.ProdList, id=good_id)
    content = {'gd_detail': gd_detail}
    return render(request, 'shopping/detail.html', content)


Shop/shopping/templates/shopping/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="{% block keyword %}小米8,小米,小米MIX25,手机{% endblock keyword %}">
    <meta name="description" content="{% block webdescription %}这是小米手机商城页面的克隆{% endblock webdescription %}">
    <title>{% block webtitle %}手机商城{% endblock webtitle %}</title>
</head>
<body>

{#    页眉#}
    {% include "shopping/header.html" %}
{#    导航栏#}
    {% include "shopping/nav.html" %}

    <main>
        {% block bodys %}
            这是网页的主题部分
        {% endblock bodys %}
    </main>

{#    页脚#}
    {% include "shopping/footer.html" %}

</body>
</html>

Shop/shopping/templates/shopping/detail.html
{% extends "shopping/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="{% block keyword %}{{ gd_detail.name }}{% endblock keyword %}">
    <meta name="description" content="{% block webdescription %}{{ gd_detail.disc }}{% endblock webdescription %}">
    <title>{% block webtitle %}立即购买-手机商城{% endblock webtitle %}</title>
</head>
<body>
    {% block bodys %}
        <h2>{{ gd_detail.name }}</h2>
        <p>{{ gd_detail.disc }}</p>
        <img src="{{ gd_detail.photo.url }}" alt="{{ gd_detail.name }}">
        {% if gd_detail.having > 0 %}
            <p>库存：{{ gd_detail.having }}</p>
        {% else %}
            <p>暂时缺货</p>
        {% endif %}
        <h3>{{ gd_detail.price }}元</h3>
    {% endblock %}
</body>
</html>

Shop/shopping/templates/shopping/footer.html
<footer>
    <center>
        &copy;Scoefield版权所有
    </center>
</footer>

Shop/shopping/templates/shopping/header.html
{% load static %}
<header>
    <center>
        <img src="{% static 'images/iPhone_logo.jpg' %}" alt="iphone logo">
    </center>
</header>

Shop/shopping/templates/shopping/home.html
{% extends "shopping/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ShowAllProd</title>
</head>
<body>
    {% block bodys %}

        {% for types, goods in type_and_goods %}
            <h2>{{ types.name }}</h2>
            <img src="{{ types.photo.url }}" alt="{{ types.name }}">
            {% for good in goods %}
                <h3><a href="{% url 'shopping:good_detail' types.id good.id %}">{{ good.name }}</a></h3>
                <p>{{ good.disc }}</p>
                <img src="{{ good.photo.url }}" alt="{{ good.name }}">
                <h4>{{ good.price }}元</h4>
            {% endfor %}
            <hr>
        {% endfor %}

    {% endblock bodys %}
</body>
</html>

Shop/shopping/templates/shopping/nav.html
<nav>
    <a href="{% url 'shopping:home' %}">所有商品</a>

        {% for phone in alltypes %}
            <a href="{% url 'shopping:single_web' phone.id %}">{{ phone.name }}</a>
        {% endfor %}

    <a href="#">购物车</a>
</nav>